---
# Per environment values which override defaults in hmpps-sharepoint-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

discoveryCronJob:
  enabled: true
  sharepoint_discovery_schedule: "*/30 8-17 * * 1-5"
  env:
    LOG_LEVEL: debug
